# Generated by Django 2.0 on 2020-05-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('store_no', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=128)),
                ('hostname', models.CharField(max_length=128)),
                ('new_hostname', models.CharField(max_length=128)),
                ('lan', models.CharField(max_length=128)),
                ('loopback', models.CharField(max_length=128)),
                ('tunnel', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=128)),
                ('open_date', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'info',
            },
        ),
        migrations.CreateModel(
            name='info_test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('Vlan1', models.CharField(max_length=128)),
                ('Vlan10', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('OpenDate', models.CharField(max_length=128)),
                ('moniDate', models.CharField(max_length=128)),
                ('internet', models.CharField(max_length=128)),
                ('ADSLUsername', models.CharField(max_length=128)),
                ('ADSLPassword', models.CharField(max_length=128)),
                ('storeNumber', models.CharField(max_length=128)),
                ('Loopback', models.CharField(max_length=128)),
                ('tunnelIP', models.CharField(max_length=128)),
                ('SN', models.CharField(max_length=128)),
                ('mark', models.CharField(max_length=128)),
                ('ADSLIP', models.CharField(max_length=128)),
                ('ADSLGateway', models.CharField(max_length=128)),
                ('TC51', models.CharField(max_length=128)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'info_test',
            },
        ),
    ]
